services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: libm-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ~/volumes/shelfmaster:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  # backend:
  #   container_name: shelfmaster_backend
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #     target: development
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   env_file:
  #     - .env
  #   ports:
  #     - "${PORT}:${PORT}"
  #   volumes:
  #     - /internals:/usr/src/app/internals
    