// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: librarians.sql

package db

import (
	"context"
)

const getLibrarianById = `-- name: GetLibrarianById :one
SELECT email, user_id, password_hash, library_id, created_at, updated_at FROM librarians WHERE user_id  = $1
`

func (q *Queries) GetLibrarianById(ctx context.Context, userID int32) (Librarian, error) {
	row := q.db.QueryRow(ctx, getLibrarianById, userID)
	var i Librarian
	err := row.Scan(
		&i.Email,
		&i.UserID,
		&i.PasswordHash,
		&i.LibraryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select email, user_id, password_hash, library_id, created_at, updated_at FROM librarians WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Librarian, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Librarian
	err := row.Scan(
		&i.Email,
		&i.UserID,
		&i.PasswordHash,
		&i.LibraryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
