// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Author struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Book struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Authorid    int32  `json:"authorid"`
	Description string `json:"description"`
}

type User struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}
