// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RoleType string

const (
	RoleTypeADMIN     RoleType = "ADMIN"
	RoleTypeUSER      RoleType = "USER"
	RoleTypeLIBRARIAN RoleType = "LIBRARIAN"
)

func (e *RoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleType(s)
	case string:
		*e = RoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleType: %T", src)
	}
	return nil
}

type NullRoleType struct {
	RoleType RoleType `json:"role_type"`
	Valid    bool     `json:"valid"` // Valid is true if RoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.RoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleType), nil
}

type Author struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Biography   pgtype.Text `json:"biography"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Nationality pgtype.Text `json:"nationality"`
}

type Book struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Authorid    int32            `json:"authorid"`
	Description string           `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type BookInventory struct {
	ID                int32 `json:"id"`
	BookID            int32 `json:"book_id"`
	TotalQuantity     int32 `json:"total_quantity"`
	AvailableQuantity int32 `json:"available_quantity"`
	LibraryID         int32 `json:"library_id"`
}

type EmailVerification struct {
	ID        int32       `json:"id"`
	Code      string      `json:"code"`
	UserID    int32       `json:"user_id"`
	Email     string      `json:"email"`
	ExpiresAt pgtype.Date `json:"expires_at"`
}

type Library struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Address     string           `json:"address"`
	PhoneNumber pgtype.Text      `json:"phone_number"`
	Email       pgtype.Text      `json:"email"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Session struct {
	ID        string           `json:"id"`
	UserID    int32            `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Fresh     pgtype.Bool      `json:"fresh"`
}

type User struct {
	ID            int32            `json:"id"`
	Email         string           `json:"email"`
	PasswordHash  string           `json:"password_hash"`
	Name          string           `json:"name"`
	MobileNumber  pgtype.Text      `json:"mobile_number"`
	Role          NullRoleType     `json:"role"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	EmailVerified pgtype.Bool      `json:"email_verified"`
}

type UserBook struct {
	UserID     int32            `json:"user_id"`
	BookID     int32            `json:"book_id"`
	BorrowedAt pgtype.Timestamp `json:"borrowed_at"`
	DueDate    pgtype.Timestamp `json:"due_date"`
}
