// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: book.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBooksByUserId = `-- name: GetBooksByUserId :many
select b.id,b.name,b.authorid,b.description,b.created_at,b.updated_at 
    from books as b join user_books as ub 
    on b.id = ub.book_id 
        where ub.user_id = $1
        order by ub.borrowed_at
`

type GetBooksByUserIdRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Authorid    int32            `json:"authorid"`
	Description string           `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetBooksByUserId(ctx context.Context, userID int32) ([]GetBooksByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getBooksByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBooksByUserIdRow
	for rows.Next() {
		var i GetBooksByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Authorid,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnBook = `-- name: ReturnBook :one
UPDATE user_books as ub 
    set returned = true 
    where ub.user_id = $1 
    and ub.book_id = $2 RETURNING ub.returned
`

type ReturnBookParams struct {
	UserID int32 `json:"user_id"`
	BookID int32 `json:"book_id"`
}

func (q *Queries) ReturnBook(ctx context.Context, arg ReturnBookParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, returnBook, arg.UserID, arg.BookID)
	var returned pgtype.Bool
	err := row.Scan(&returned)
	return returned, err
}

const saveBookInventory = `-- name: SaveBookInventory :one
insert into  book_inventory (book_id,total_quantity,available_quantity,library_id)
    values($1,$2,$3,$4) RETURNING id
`

type SaveBookInventoryParams struct {
	BookID            int32 `json:"book_id"`
	TotalQuantity     int32 `json:"total_quantity"`
	AvailableQuantity int32 `json:"available_quantity"`
	LibraryID         int32 `json:"library_id"`
}

func (q *Queries) SaveBookInventory(ctx context.Context, arg SaveBookInventoryParams) (int32, error) {
	row := q.db.QueryRow(ctx, saveBookInventory,
		arg.BookID,
		arg.TotalQuantity,
		arg.AvailableQuantity,
		arg.LibraryID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const saveBookQuery = `-- name: SaveBookQuery :one
insert into books(name,authorid,description,created_at,updated_at,isbn_10,isbn_13,edition,publisher,date_published)
    values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, name, authorid, description, created_at, updated_at, isbn_10, isbn_13, edition, publisher, date_published
`

type SaveBookQueryParams struct {
	Name          string           `json:"name"`
	Authorid      int32            `json:"authorid"`
	Description   string           `json:"description"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	Isbn10        pgtype.Text      `json:"isbn_10"`
	Isbn13        pgtype.Text      `json:"isbn_13"`
	Edition       string           `json:"edition"`
	Publisher     string           `json:"publisher"`
	DatePublished pgtype.Timestamp `json:"date_published"`
}

func (q *Queries) SaveBookQuery(ctx context.Context, arg SaveBookQueryParams) (Book, error) {
	row := q.db.QueryRow(ctx, saveBookQuery,
		arg.Name,
		arg.Authorid,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Isbn10,
		arg.Isbn13,
		arg.Edition,
		arg.Publisher,
		arg.DatePublished,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Authorid,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Isbn10,
		&i.Isbn13,
		&i.Edition,
		&i.Publisher,
		&i.DatePublished,
	)
	return i, err
}
